### PR TITLE
Encryption and decryption

### PR DESCRIPTION
**Pull request by Coddzilla**

### CODE REVIEW

**Review by xtheshumanator — DISMISSED** [review]
approved

**Review by xtheshumanator — DISMISSED** [review]
approved

**Review by WillemTaylor — DISMISSED** [review]

**Comment by WillemTaylor** [comment]
conflicts:
requirements.txt
ssc/Invites/invites.py
ssc/Utils/db_ops.py
ssc/Workspaces/workspaces.py
ssc/server.py

**Review by xtheshumanator — APPROVED** [review]
approved

**Pull request merged**
